### ISSUE TITLE
wymeditor could not find all assets

### ISSUE THREAD

**Issue by mattherick** [parndt/refinerycms-wymeditor#15]
I have to include following assets directly into my public folder:

    public/assets/refinery/formatting.css
    public/assets/refinery/theme.css
    public/assets/wymeditor/lang/de.js
    public/assets/skins/refinery/wymiframe.css

to remove a few 404 errors.. why are these files not loaded correctly through the rails asset pipeline?

Further I have a problem with precompiled assets:

    "NetworkError: 404 Not Found - http://my-domain.com/assets/wymeditor/skins/refinery/html5/h1-34fd10a7c7f09d1652329c96543a039e.png"
    "NetworkError: 404 Not Found - http://my-domain.com/assets/wymeditor/skins/refinery/html5/p-e482be71ffd131e6c25340378e37ae98.png

And if I take a look into my public assets folder on production I can see following files in the public/assets/wymeditor/skins/refinery/html5 directory:

    h1-8822cc5e930e7e2fe2d754b4ea64780c.png
    h1.png
    p-8d766d51f785ed9f10b2d934e29b79ef.png
    p.png

So is there something cached for the wymeditor? Or why does the editor requests "old" precompiled assets? If I use the h2-tag odr h3-tag I also get the same 404 not found error.
Any ideas what I am doing wrong or what could solve my problem?

I only have these problems on production btw.

**Comment by kingduggan1** [comment]
I'm having the same problems on my production server as mattherick with these files:

public/assets/refinery/formatting.css
public/assets/refinery/theme.css
public/assets/skins/refinery/wymiframe.css

Below is what the console is reporting when trying to load these assets.
 
![image](https://cloud.githubusercontent.com/assets/71069/6271925/c1152dfc-b829-11e4-83bb-29959d88cf17.png)

**Comment by kingduggan1** [comment]
Don't think this problem is a refinery issue but more of a compiling assets problem. Once the assets are compiled during a capistrano deploy they get served from the public/assets folder. However the file names will look like this:
formatting-a3f5a4c90b18d83bac10f3be5c036af2.css

rails usually will serve that file in production but for some reason refinery is loooking for a filename like this:

formatting.css

If I do a ' cp formatting-a3f5a4c90b18d83bac10f3be5c036af2.css formatting.css ' to create a file with the exact name the asset will be served. This is only happening on these three files in my production environment. All other assets I can leave with the compiled asset name and it will be served.  

Just wanted to give an update on my findings.

**Comment by parndt** [comment]
Ah, yes, we're probably not linking to those files properly so they're not using the right, compiled, path..

**Comment by riceboy6888** [comment]
Same problem for me. Is there a fix instead of doing it manually ?

**Comment by parndt** [comment]
@riceboy6888 @mattherick @drobsokc I figured this out today, does #26 fix your issue?

**Comment by simi** [comment]
Also https://github.com/alexspeller/non-stupid-digest-assets can be used as workaround.

**Comment by darmens** [comment]
I had the same issue and I fixed most of it referencing the edge version of `refinerycms-wymeditor` from the Gemfile. But it still can't find `/assets/wymeditor/lang/it.js`, and I still get this error:

`"NetworkError: 404 Not Found - http://example.com/assets/wymeditor/lang/it.js"`

What can I do?

**Comment by andywenk** [comment]
@parndt the problem is not fixed as far as I can see:

<img width="1280" alt="screen shot 2015-11-08 at 22 24 21" src="https://cloud.githubusercontent.com/assets/51517/11022764/92b8676e-8667-11e5-975a-43fc2a9fe369.png">

**Comment by parndt** [comment]
@andywenk which version are you using?

**Comment by andywenk** [comment]
@parndt the one shipped with refinery master:

    gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'
    gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
    gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
    gem 'refinerycms-authentication-devise', '~> 1.0'

**Comment by andywenk** [comment]
@parndt any news on this - I still have this problem - thanks!

**Comment by andywenk** [comment]
for the record - @simi 's suggestion with simply including https://github.com/alexspeller/non-stupid-digest-assets does fix the problem ... thanks
