### ISSUE TITLE
dont have config  files

### ISSUE THREAD

**Issue by kreker92** [parndt/refinerycms-wymeditor#36]
I dont have any wymeditor files for editing white list tags

Gemfile:
```
gem 'refinerycms', '~> 3.0'
gem 'refinerycms-i18n'
gem 'refinerycms-blocks', :git => 'https://site.com/git/refinerycms-blocks'

gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.1']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'
gem 'refinerycms-search', github: 'refinery/refinerycms-search', branch: 'master'
gem 'refinerycms-page-images', '~> 3.0.0', github: "refinery/refinerycms-page-images", branch: "master"
```

In Gemfile.lock:

```
refinerycms-wymeditor (1.0.7)
      refinerycms-core (>= 3.0.0, < 5.0)

DEPENDENCIES
  refinerycms-wymeditor (~> 1.0, >= 1.0.6)
```

**Comment by bricesanchez** [comment]
Did you install `refinerycms-wymeditor` after generating the app?

If yes, did you run this command ?
```
rails generate refinery:wymeditor
```

**Comment by kreker92** [comment]
Yes, I've added this gem after generation the app.
I'm runing it but, I dont know why, nothing is heppening. Process is not finishing.
I've install clean refinery, then launch rails generate refinery:wymeditor wymeditor. It says that installing just creates file config/initializers/refinery/wymeditor.rb
I've copied it to my real project and insert:
```
# encoding: utf-8
Refinery::Wymeditor.configure do |config|
  # Add extra tags to the wymeditor whitelist e.g. = {'tag' => {'attributes' => {'1' => 'href'}}} or just {'tag' => {}}
  config.whitelist_tags = {"li"=>{"attributes"=>{"1"=>"data-slide-id"}}}
end
```
And it still doesnt work

**Comment by bricesanchez** [comment]
What is your version of refinerycms ? 

3.0.4 (unreleased) whitelist all data attributes in frontend : 
https://github.com/refinery/refinerycms/pull/3187

So you can use the 3-0-stable branch : 

```
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: '3-0-stable'
```

**Comment by kreker92** [comment]
No, its not.
I've installed refinery on new clean rails project. Install wymeditor too.
I've installed it. Now I have config file config/initializers/refinery/wymeditor.rb
It contents:
```
# encoding: utf-8
Refinery::Wymeditor.configure do |config|
  # Add extra tags to the wymeditor whitelist e.g. = {'tag' => {'attributes' => {'1' => 'href'}}} or just {'tag' => {}}
  config.whitelist_tags = {'li' => {'attributes' => {'1' => 'data-slide-id'}}}
end
```
And I have result:
`<li data-slide-id="slide1">qwe</li>`
But when I insert real content it has strange thing:
```
<ul>
                        <li class="active"> slide1</li>
                        <li data-slide-id="slide2">slide2 </li>
                        <li data-slide-id="slide3">slide3 </li>
                    </ul>
```
Attribute class removes data-slide-id.

Trying to add class to white list doesn't helps.

**Comment by bricesanchez** [comment]
You are right, i can reproduce your, let me check why it does not whitelist data attributes.

**Comment by bricesanchez** [comment]
Could you temporary test this branch to see if it fixes your problem ? 

```ruby
gem 'refinerycms', github: 'refinery/refinerycms', branch: 'bugfix/allow-data-attr-3-0-rebase'
```

Please continue this discussion in the pull request: https://github.com/refinery/refinerycms/pull/3217
