### ISSUE TITLE
Some css styles are missing after upgrade on refinery 4.0.0

### ISSUE THREAD

**Issue by xnagpa** [parndt/refinerycms-wymeditor#47]
Steps to reproduce the issue: 
1. I setup clear new application with refinery 4.0.0 
2. I do `RAILS_ENV=production rails assets:precompile`
3. I start my app with `RAILS_ENV=production rails s`
4. skin.css and wyeditor.css are missing(404) when I try to create or edit page

**Comment by bricesanchez** [comment]
i can confirm the bug on production ENV. I don't know yet how to fix it. Any thoughts @parndt?

**Comment by bricesanchez** [comment]
I found the problem: https://github.com/refinery/refinerycms/blob/master/core/app/views/refinery/admin/_head.html.erb#L9-L12

If i remove the `{ skip_pipeline: true }` option it works in dev and in prod env.
