### ISSUE TITLE
Issue with WYM Editor in production

### ISSUE THREAD

**Issue by samuelpbowman** [parndt/refinerycms-wymeditor#48]
When running the app in development, the administrative backend's WYM looks like this
![wym_css_proper](https://user-images.githubusercontent.com/8527824/31594465-0fbf2c98-b203-11e7-989c-132252f6f4cc.png)
However, after deploying (assets are always precompiled at deploy time), the production environment looks like
![wym_css_issue](https://user-images.githubusercontent.com/8527824/31594483-28a6466a-b203-11e7-921a-e75bdb796853.png)
I know that there was a bug for some CSS issues, so I wanted to see if there was anything you all could think of. I'll be happy to answer any questions you may have.

**Comment by bricesanchez** [comment]
It's fixed on this PR and will be released with refinerycms 4.0.1 :)
https://github.com/refinery/refinerycms/pull/3318
