### ISSUE TITLE
Cannot update to Rails 5.2.2

### ISSUE THREAD

**Issue by shadydealer** [parndt/refinerycms-wymeditor#51]
We're trying to upgrade from rails 5.1.0 to rails 5.2.2 to use the following funcitonality: https://github.com/rails/rails/commit/1813350f0927dde01a11ebbd33a8f6b0deacd073

But we can't seem to upgrade because:

```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    actionpack

    actionpack-action_caching was resolved to 1.2.0, which depends on
      actionpack (>= 4.0.0, < 6)

    rails (~> 5.2.2) was resolved to 5.2.2, which depends on
      actionpack (= 5.2.2)

    refinerycms-wymeditor was resolved to 2.0.0, which depends on
      refinerycms-core (>= 4.0.0.dev, < 5.0) was resolved to 4.0.3, which depends on
        actionpack (>= 5.1.0, < 5.2)

    refinerycms-i18n was resolved to 4.0.1, which depends on
      routing-filter (>= 0.4.0) was resolved to 0.6.2, which depends on
        actionpack (>= 4.2, < 6)
```

**Comment by bricesanchez** [comment]
Hi @shadydealer,

You should use the master branch of Refinery CMS to upgrade to rails 5.2 : 
https://www.refinerycms.com/blog/posts/refinery-cms-5-0-sneak-peek

Thanks,

Brice

**Comment by thebravoman** [comment]
Wow, thanks @bricesanchez @shadydealer. Just came looking for this and it is resolved :+1:
