### ISSUE TITLE
Saving page results in Internal Server Error

### ISSUE THREAD

**Issue by veger** [parndt/refinerycms-wymeditor#52]
I Created a new page, set title, parent and added some content.

When clicking save I got this error:
```
ActionView::Template::Error (undefined method `find_asset' for nil:NilClass):
     5:     <meta charset='<%= ::Rails.application.config.encoding %>' />
     6:     <meta httpequiv="XUACompatible" content="IE=edge,chrome=1" />
     7:     <%= stylesheet_link_tag "wymeditor/skins/refinery/wymiframe", :media => "all" %>
     8:     <%= stylesheet_link_tag "formatting", :media => "all" if Rails.application.assets.find_asset('formatting.css') %>
     9:     <%= stylesheet_link_tag "theme", :media => "all" %>
    10:     <%= javascript_include_tag 'modernizr-min' %>
    11:   </head>
```

I am using (pre-)compiled assets on my production environment.

The error seems to be related to https://github.com/rails/sprockets-rails/issues/311

**Comment by mzagaja** [comment]
On my staging server if I set `config.assets.compile = false` the server will fail to serve the IFRAME and throw a 500 error on the request. The result is WYMEDITOR does not load. Digging into the logs we learn that it is due to:
```
F, [2020-01-21T15:48:10.401556 #28152] FATAL -- : [ea9ca180-a088-4e55-99ce-26fb664ba8c3] ActionView::Template::Error (undefined method `find_asset' for nil:NilClass):
F, [2020-01-21T15:48:10.401752 #28152] FATAL -- : [ea9ca180-a088-4e55-99ce-26fb664ba8c3]      5:     <meta charset='<%= ::Rails.application.config.encoding %>' />
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]      6:     <meta httpequiv="XUACompatible" content="IE=edge,chrome=1" />
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]      7:     <%= stylesheet_link_tag "wymeditor/skins/refinery/wymiframe", :media => "all" %>
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]      8:     <%= stylesheet_link_tag "formatting", :media => "all" if Rails.application.assets.find_asset('formatting.css') %>
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]      9:     <%= stylesheet_link_tag "theme", :media => "all" %>
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]     10:     <%= javascript_include_tag 'modernizr-min' %>
[ea9ca180-a088-4e55-99ce-26fb664ba8c3]     11:   </head>
```

The temporary fix is to set `config.assets.compile = true` but this is [not ideal](https://stackoverflow.com/a/8827757/2149359). A suggested fix is [here](https://github.com/rails/sprockets-rails/issues/237#issuecomment-204156053) if #53 is not working.

**Comment by bricesanchez** [comment]
Hi @mzagaja, Did you succeed to fix the bug without using `config.assets.compile = true`

**Comment by mzagaja** [comment]
Apologies for missing this note, @bricesanchez. I have not yet fixed this bug, but this project has been on the backburner until our next funding round. I might be able to test/work on the approach in https://github.com/parndt/refinerycms-wymeditor/pull/53 when this opens up.

**Comment by Unknown-Guy** [comment]
Having the same issue in all environments except development. I can't find any info why that line is even needed. The `formatting` wont get compiled even if it exists.

**Comment by Unknown-Guy** [comment]
95c4adc removed `formatting.css` so the `stylesheet_link_tag` line looks obsolete to me.

Overriding the view in our app and removing the line fixed the issue.
